[default]
extend-ignore-re = ["call_[[:alnum:]]+"]

[default.extend-words]
# Don't correct the state ND
ND = "ND"
# Don't correct pirates using acronyms
mornin = "mornin"

[files]
extend-exclude = ["docs/assets", "tests/resources/"]

